Repository FromDoppler/doppler-automation-editor, pull requests merged in 2023-07, with the labels that each got.

#39 DOP-1413 - Update content template campaign mark
  src/partials/templates/dp-templates.html
Labels: size/XS

#41 DOP-1407 - resolve visual issue in smart subject button
  src/css/app/templates/automation/_editor-panel.scss
Labels: size/XS

#40 DOP-1408 - Tooter border issue
  src/css/app/templates/automation/_editor.scss
  src/directives/automation/editor/dpEditorListsGrid.js
  src/directives/automation/editor/footer/dpEditorFooter.js
  src/partials/automation/editor/directives/dp-editor-domains-grid.html
  src/partials/automation/editor/directives/dp-editor-import-html.html
  src/partials/automation/editor/directives/dp-editor-lists-grid.html
  src/partials/automation/editor/directives/footer/dp-editor-footer.html
Labels: size/L

#42 feat: update intl-tel-input library
  package-lock.json
  package.json
  src/lib/intlTelInput/intlTelInput.js
  src/lib/intlTelInput/intlTelInput.min.js
  src/lib/intlTelInput/utils.js
  webpack2.config.js
Labels: size/XXL

#43 DOP-1427 - Set template ribbon content
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/templates/dp-templates.html
Labels: size/XS

#44 DOP-1430 - update automation template content
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/M
