Repository FromDoppler/doppler-automation-editor, pull requests merged in 2023-06, with the labels that each got.

#18 DOP-1348 - Add template preview
  src/constants.js
  src/controllers/automation/automationGridCtrl.js
  src/css/app/templates/_types.scss
  src/css/app/templates/automation/_editor-headerAndFooter.scss
  src/css/images/automation_template/automation-template_1_en.jpg
  src/css/images/automation_template/automation-template_1_es.jpg
  src/css/images/automation_template/automation-template_2_en.jpg
  src/css/images/automation_template/automation-template_2_es.jpg
  src/css/images/automation_template/automation-template_3_en.jpg
  src/css/images/automation_template/automation-template_3_es.jpg
  src/css/images/automation_template/automation-template_4_en.jpg
  src/css/images/automation_template/automation-template_4_es.jpg
  src/directives/automation/editor/dpEditorTemplate-preview.js
  src/directives/automation/editor/dpEditorTemplate.js
  src/directives/automation/editor/dpEditorTypes.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-template-preview.html
  src/partials/automation/editor/directives/dp-editor-template.html
  src/partials/automation/editor/directives/dp-editor-types.html
  src/partials/automation/taskGrid.html
Labels: size/L

#19 DOP-1372 - Update mfe editor
  src/controllers/automation/automationGridCtrl.js
  src/css/app/templates/automation/_editor-panel.scss
  src/directives/automation/editor/panel/dpEditorPanelSms.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-types.html
  src/partials/automation/editor/directives/panel/dp-editor-panel-sms.html
Labels: size/M

#20 DOP-1648 - fix visual issue
  src/partials/automation/editor/directives/dp-editor-template-preview.html
Labels: size/XS

#21 DOP-1375 - Group all js file on app.js
  webpack2.config.js
Labels: size/XS

#22 DOP-1379 - Sort automation template cards
  src/directives/automation/editor/dpEditorTemplate.js
Labels: size/S

#23 DOP-1380 - Set help content automation template
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-template-preview.html
  src/partials/automation/editor/directives/dp-editor-template.html
Labels: size/S

#24 DOP-1374 - Remove replace redirection mfe
  package-lock.json
  package.json
  src/automationEditorModule.js
  webpack2.config.js
Labels: size/S

#25 Fix hasBlockedList when suscriptionLists is not defined
  src/services/automation/editor/automation.js
Labels: size/S

#26 Remove BOM from partial html files
  src/partials/automation/editor/directives/header/dp-editor-save.html
  src/partials/automation/editor/directives/header/dp-editor-undoredo.html
  src/partials/automation/editor/directives/panel/dp-editor-panel-step-tip.html
  src/partials/automation/editor/lists-grid.html
  src/partials/controlPanel/landing-pages-domains/configureCustomDomain.html
  src/partials/controlPanel/landing-pages-domains/domainVerificationError.html
  src/partials/shared/checkbox.html
  src/partials/shared/ellipsis-with-tooltip.html
  src/partials/shared/graph.html
  src/partials/shared/loader.html
  src/partials/shared/loading.html
  src/partials/shared/modalProcessFile.html
  src/partials/shared/modalYesOrNo.html
  src/partials/shared/preview.html
  src/partials/templates/empty.html
Labels: size/M

#27 DOP-1387 - fix hasBlockedList
  src/services/automation/editor/automation.js
Labels: size/XS

#28 Revert "Merge pull request #24 from FromDoppler/DOP-1374-automation-editor-switch"
  package-lock.json
  package.json
  src/automationEditorModule.js
  webpack2.config.js
Labels: size/S

#29 DOP-1374 - Replace automation editor by the new MFE
  package-lock.json
  package.json
  src/automationEditorModule.js
  webpack2.config.js
Labels: size/S

#30 fix: set the initial condition like selected
  src/directives/automation/editor/components/initialConditions/dpEditorDynamicContentCondition.js
Labels: size/XS

#32 fix: set "unsavedChanges" flag like true
  src/directives/automation/editor/components/initialConditions/dpEditorDynamicContentCondition.js
Labels: size/S

#31 DOP-1393 - Automation campaing template fix
  src/css/app/templates/_templates.scss
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/templates/dp-templates.html
Labels: size/L

#33 DOP-1393 - declare undefined object
  src/automationEditorModule.js
Labels: size/XS

#34 DOP-1394 - add polling service
  src/directives/dp-on-error-src.js
  src/services/shared/pollService.js
Labels: size/M

#35 DOP-1400 Set automation template card as new feature
  src/css/app/templates/_types.scss
  src/partials/automation/editor/directives/dp-editor-template.html
  src/services/automation/taskService.js
Labels: size/S

#37 DOP-1400 - Set template card as new feature fix
  src/css/app/templates/_types.scss
  src/partials/automation/editor/directives/dp-editor-template.html
Labels: size/XS

#36 Dop 1406 fix cart validation
  src/directives/automation/editor/components/initialConditions/dpEditorDynamicContentCondition.js
  src/directives/automation/editor/panel/initialConditions/dpEditorPanelDynamicContentCondition.js
Labels: size/M

#38 DOP-1409 - Add preview controller
  src/controllers/shared/index.js
Labels: size/XS
