Repository FromDoppler/doppler-automation-editor, pull requests merged in 2024-10, with the labels that each got.

#91 DOP-1649 - update multimedia link
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
  src/services/automation/editor/whatsappDataservice.js
Labels: size/L

#92 DOP-1649 - Whatsapp update response object
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
Labels: size/XS

#93 DOP-1649 multimedia template wsp file upload fixs
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
  src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Labels: size/M

#94 [DONT MERGE] [DOI-1617] Add empretienda option
  src/constants.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-types.html
Labels: size/S

#95 doi-1617 add missing translation and fix typo
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/XS

#96 chore: remove line break
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/XS

#99 Update whatsapp help link
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Labels: size/XS

#98 DOP-1649 - Multimedia template wsp file upload fix
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
  src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Labels: size/M
