Repository FromDoppler/doppler-automation-editor, pull requests merged in 2024-11, with the labels that each got.

#100 [DOI-1692] Exclude abandoned cart time option when mercadoshops
  src/directives/automation/editor/panel/initialConditions/dpEditorPanelDynamicContentCondition.js
Labels: size/XS

#101 DOP-1677 adapt template category
  src/directives/dp-templates.js
  src/services/automation/editor/components/AutomationComponent.js
Labels: size/S

#102 DOP-1507 - Template frequent buyer
  src/css/app/templates/_types.scss
  src/css/images/automation_template/automation-template_11_en.jpg
  src/css/images/automation_template/automation-template_11_es.jpg
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-template.html
Labels: size/M

#103 DOP-1644 - Add customer anniversary coupon template
  src/css/app/templates/_types.scss
  src/css/images/automation_template/automation-template_12_en.jpg
  src/css/images/automation_template/automation-template_12_es.jpg
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/S

#104 DOP-1510 - Add Purchase completed coupon flow
  src/css/app/templates/_types.scss
  src/css/images/automation_template/automation-template_13_en.jpg
  src/css/images/automation_template/automation-template_13_es.jpg
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/S

#105 DOP-1688 - Content update
  src/css/app/templates/_types.scss
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/S

#106 DOP-1658 - Whatsapp report enabled
  src/directives/automation/editor/panel/dpEditorPanel.js
  src/directives/automation/editor/panel/initialConditions/dpEditorPanelCampaignBehaviorCondition.js
  src/partials/automation/taskGrid.html
Labels: size/S

#107 DOP-1690 - Abandonded Cart coupon template
  src/css/app/templates/_types.scss
  src/css/images/automation_template/automation-template_14_en.jpg
  src/css/images/automation_template/automation-template_14_es.jpg
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/S

#109 improve whatsapp component
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
Labels: size/XS
