Repository FromDoppler/doppler-automation-editor, pull requests merged in 2024-08, with the labels that each got.

#71 DOP-1592 - Initial condition fix
  src/partials/automation/editor/directives/panel/initialConditions/dp-editor-panel-campaign-behavior-condition.html
Labels: size/XS

#72 DOP-1597 - Add params for sendWhatsappTest
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
Labels: size/XS

#73 DOP-1616 - Update automation template order
  src/directives/automation/editor/dpEditorTemplate.js
Labels: size/XS

#74 Dop 1618 use new endpoint to obtain replication types list
  src/controllers/shared/modalReplicateAutomationCtrl.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/services/automation/taskService.js
Labels: size/S

#75 DOP-1615 - Enable WhatsApp component for each automation
  src/services/automation/editor/componentsDataservice.js
Labels: size/XS

#77 [DOW-43] replace content for pending and confirmed order
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-types.html
Labels: size/XS

#78 DOP-1620 - Update request to send WhatsApp test
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Labels: size/M

#76 DOP-1619 - Whatsapp template preview
  src/css/doppler-common/modules/_forms.scss
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
  src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
  src/services/automation/editor/components/WhatsappComponent.js
Labels: size/S

#79 DOP-1679 - fix whatsapp preview
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
Labels: size/S

#80 Dop 1509 add pending payment reminder
  src/css/app/templates/_types.scss
  src/css/images/automation_template/automation-template_9_en.jpg
  src/css/images/automation_template/automation-template_9_es.jpg
  src/directives/automation/editor/dpEditorTemplate.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/S

#81 fix: add line breaks and bolds in the template preview description
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-template-preview.html
Labels: size/XS

#82 Dop 1614 add confirmed payment template
  src/css/app/templates/_types.scss
  src/css/images/automation_template/automation-template_10_en.jpg
  src/css/images/automation_template/automation-template_10_es.jpg
  src/directives/automation/editor/dpEditorTemplate.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
Labels: size/S

#83 fix: pending payment preview image in english
  src/css/images/automation_template/automation-template_9_en.jpg
Labels: size/XS

#84 DOP-1583 - WhatsApp link fix
  src/directives/automation/editor/canvas/dpEditorNewStep.js
  src/directives/automation/editor/dpEditorTemplate.js
  src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
  src/i18n/automation-dicc-en.js
  src/i18n/automation-dicc-es.js
  src/partials/automation/editor/directives/dp-editor-template.html
  src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
  src/services/automation/editor/whatsappDataservice.js
Labels: size/M
